language: node_js
sudo: false
node_js:
  - '0.10'
cache:
  directories:
    - node_modules
    - bower_components
before_script:
  - export CI=true
  - bower install
install:
  - npm install -g bower
  - npm install -g gulp
  - npm install
  - gulp minify
script:
  - node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=PhantomJS
  